CREATE TABLE LIBRARY(
    userNo NUMBER,
    userId VARCHAR2(20),
    userPwd VARCHAR2(20),
    userName VARCHAR2(20),
    GENDER CHAR(3),
    age NUMBER,
    EMAIL VARCHAR2(50),
    PHONE VARCHAR2(13),
    address VARCHAR2(20),
    
    title VARCHAR2(50),
    enrollDate DATE
);
SELECT * FROM LIBRARY;
COMMENT ON COLUMN LIBRARY.userNo IS '회원번호'; 
COMMENT ON COLUMN LIBRARY.userId IS '회원아이디';
COMMENT ON COLUMN LIBRARY.userPwd IS '회원비밀번호';
COMMENT ON COLUMN LIBRARY.userName IS '회원명';
COMMENT ON COLUMN LIBRARY.GENDER IS '성별(M/F)';
COMMENT ON COLUMN LIBRARY.age IS '나이'; 
COMMENT ON COLUMN LIBRARY.EMAIL IS '이메일';
COMMENT ON COLUMN LIBRARY.PHONE IS '전화번호';
COMMENT ON COLUMN LIBRARY.address IS '회원주소';
COMMENT ON COLUMN LIBRARY.title IS '신청(희망)서적';
COMMENT ON COLUMN LIBRARY.enrollDate IS '회원가입일';

INSERT INTO LIBRARY VALUES(1, 'USER01', 'PASS01', '홍길동', 'M', NULL, NULL, NULL,NULL,NULL,NULL);
ROLLBACK;
create SEQUENCE home_test;

SELECT
    * FROM home_sequences;